// ModelMod: 3d data snapshotting & substitution program.
// Copyright(C) 2015,2016 John Quigley

// This program is free software : you can redistribute it and / or modify
// it under the terms of the GNU Lesser General Public License as published by
// the Free Software Foundation, either version 2.1 of the License, or
// (at your option) any later version.

// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.See the
// GNU General Public License for more details.

// You should have received a copy of the GNU Lesser General Public License
// along with this program.If not, see <http://www.gnu.org/licenses/>.

namespace ModelMod

open System
open System.Collections.Generic
open System.IO

open Microsoft.Xna.Framework

open CoreTypes

/// Utilities for comparing a Mod to a Reference and copying any required data from the Ref to the Mod
/// (such as blend weight information).
module MeshRelation =
    let private log = Logging.getLogger("MeshRelation")

    /// Triangle data (essentially a de-normalized version of IndexedTri).
    type Tri = {
        // three elements each
        Position: Vec3F[];
        TexCoord: Vec2F[];
        Normal: Vec3F[];
    }

    type MVProjections = { X:float ; Y:float ; Z:float }

    /// Data required for CPU animations.  These are currently unimplemented, but this is some of the
    /// data that is needed using a method I prototyped before.  That method is roughly as follows
    /// 1) for each mod vert, compute an offset vector from the ref to the mod, with both in a neutral/root position
    /// The offset vector is computed from nearest vertex of the nearest triangle to the mod vert.  The centroids
    /// of each triangle containing the ref vert are used to find the nearest triangle to the mod vert (normals
    /// should probably be used as well so that double-sided triangles don't cause problems).
    /// 2) At run-time, on each frame, whenever the original ref is drawn, lock the VB and read back the
    /// ref data into system memory.  For each mod vert, re-compute the (current) projection triangle, and compute
    /// the projection vectors again.  Use the projection vectors to offset the ref verts.
    /// 3) Write a new vb using the new ref verts; draw it, and Voila, its the animated mod.
    /// Provided you aren't doing this for a huge amount of data, the performance hit barely registers (though, to be
    /// fair, the original code was in C++, so I don't know how well managed code would handle it).
    type CPUSkinningData = {
        UseRef: bool
        VecToModVert: Vec3F
        ModProjections: MVProjections
        RefIndices: int[]
        RefNormal: Vec3F
        //refTexCoord: Vec2F
    }

    /// Relation data for each ref/mod vert pair.
    type VertRel = {
        Distance: float32
        RefPointIdx: int
        ModVertPos: Vec3F
        RefVertPos: Vec3F
        CpuSkinningData: CPUSkinningData option
    }

    /// Utility module to cache mesh relations to disk.  Because these 
    /// are so inefficient to build (see code below) this dramatically speeds
    /// up reload times since most mods and references aren't changing 
    /// from run-to-run.
    /// 
    /// This uses FsPickler which is apparently very sensitive to FSharp.Core
    /// versions - it was failing until I locked everything to use 4.4.3.0 
    /// (which is what VS2019 wants to use) everywhere.  This is also fixable
    /// by using a .config file next to the injected exe, which contains a 
    /// binding redirect, but since that requires dropping extra conf files 
    /// everywhere I chose not to do that.
    /// Note this code was mostly generated by LLM (OpenAI GPT 5.2-Thinking)
    module MeshRelDiskCache =
        open System.IO.Compression
        open MBrace.FsPickler

        open BinCacheTypes

        let mutable verboseLog = Logging.getNullLogger() 

        let setVerboseLog enabled = 
            verboseLog <- if enabled then Logging.getLogger("MeshRelDiskCache") else Logging.getNullLogger()

        let private ser = FsPickler.CreateBinarySerializer()
        let private cacheVersion = 2

        type Entry = {
            Version: int
            Mod: MeshSig
            Ref: MeshSig
            VertRels: VertRel[]
        }

        let private mkModSig (md: DBMod) =
            mkSig md.MeshPath md.Type md.MeshReadFlags

        let private mkRefSig (r: DBReference) =
            mkSig r.MeshPath ModType.Reference r.MeshReadFlags
    
        let private key (modName: string) (refName: string) =
            let s = modName.ToLowerInvariant() + "|" + refName.ToLowerInvariant()
            use sha = System.Security.Cryptography.SHA256.Create()
            sha.ComputeHash(System.Text.Encoding.UTF8.GetBytes(s))
            |> Seq.map (fun b -> b.ToString("x2"))
            |> String.concat ""
    
        let relPath (cacheDir: string) modName refName =
            Path.Combine(cacheDir, "MeshRelations", key modName refName + ".bin.gz")
    
        let tryLoad (cacheDir: string) (md: DBMod) (r: DBReference) : VertRel[] option =
            let p = relPath cacheDir md.Name r.Name
            verboseLog.Info "[meshrelcache]: looking for cache entry: %s" p
            if not (File.Exists(p)) 
            then 
                verboseLog.Info "[meshrelcache]: cache miss (file not found)"
                None
            else
                verboseLog.Info "[meshrelcache]: cache file found, checking freshness..."
                use fs = File.OpenRead(p)
                use gz = new GZipStream(fs, CompressionMode.Decompress)
                let e = ser.Deserialize<Entry>(gz)
    
                if e.Version <> cacheVersion 
                then
                    verboseLog.Info "[meshrelcache]: cache miss (version mismatch)" 
                    None
                else
                    let ms = mkModSig md
                    let rs = mkRefSig r
                    if e.Mod = ms && e.Ref = rs 
                    then
                        verboseLog.Info "[meshrelcache]: cache hit for mod '%s' and ref '%s'" md.Name r.Name 
                        Some e.VertRels 
                    else
                        verboseLog.Info "[meshrelcache]: cache miss (mod or ref changed)" 
                        None
    
        let save (cacheDir: string) (md: DBMod) (r: DBReference) (vrs: VertRel[]) =
            let dir = Path.Combine(cacheDir, "MeshRelations")
            Directory.CreateDirectory(dir) |> ignore
            let p = relPath cacheDir md.Name r.Name
            let tmp = p + ".tmp"

            log.Info "[meshrelcache]: creating bincache entry: %A for mod=%A ref=%A" tmp md.Name r.Name
    
            let e =
                { 
                    Entry.Version = cacheVersion
                    Mod = mkModSig md
                    Ref = mkRefSig r
                    VertRels = vrs 
                }
    
            use fs = File.Create(tmp)
            use gz = new GZipStream(fs, CompressionMode.Compress)
            ser.Serialize(gz, e)
    
            if File.Exists(p) then File.Delete(p)
            File.Move(tmp, p)
    
    type MeshRelation(md:DBMod, ref:DBReference, binCacheDir:string) =
        let verifyAndGet(name:string) (mo:Lazy<Mesh> option) =
            match mo with
            | None -> failwithf "cannot build vertrel for mod/ref with no mesh: %A" name
            | Some (m) -> m

        let mutable modMesh = None
        let mutable refMesh = None

        let mutable md = md
        let mutable ref = ref

        let updateDBElems (newMd:DBMod) (newRef:DBReference) =
            // can change the mod entries if the meshes didn't change or if the _only_ thing that changed is the cached flag
            // (and it was set to true)
            let newModMesh = (verifyAndGet newMd.Name newMd.Mesh).Force()
            let newRefMesh = (newRef.Mesh.Force())

            let oldModMesh = {modMesh.Value with Cached = true}
            let oldRefMesh = {refMesh.Value with Cached = true}

            // perfnote: these are deep equality compares of the structs
            if newModMesh <> oldModMesh then failwithf "updateDBElems: cannot change mod mesh; make a new mesh relation"
            if newRefMesh <> oldRefMesh then failwithf "updateDBElems: cannot change ref mesh; make a new mesh relation"
            md <- newMd
            ref <- newRef

        // Note: if this calculation is modified in the future to use something
        // other than mesh data, the caching assumptions on reload may change
        // (see `loadModDB`)

        let buildTris (mesh:Mesh) =
            let refMesh = refMesh.Value
            let tris = mesh.Triangles |> Array.map (fun iTri ->
                    let derefed = iTri.Verts |> Array.map (fun vtn ->
                            let pos = refMesh.Positions.[vtn.Pos]
                            let tc = Vector2(0.f,0.f) // refMesh.UVs.[vtn.T]
                            let nrm = Vector3(1.f,0.f,0.f) //refMesh.Normals.[vtn.N]

                            (pos,tc,nrm)
                        )
                    let pos,tc,nrm = derefed |> Array.unzip3
                    { Tri.Position = pos; Tri.TexCoord = tc; Tri.Normal = nrm }
                )
            tris

        // Build a fast exclusion filter (modIdx, refIdx) -> bool by precomputing
        // normalized lookup tables from the per-vertex annotation lists.
        //
        // Equivalent behavior to the previous list/string-based isExcluded:
        //   - Ref vert is excluded if it has a group annotated "EXCLUDE".
        //   - Ref vert is excluded if mod has "Exclude.X" and ref has group "X".
        //   - Ref vert is excluded if mod has "Include.X" and ref does NOT have group "X".
        //   - Otherwise included.
        // Comparisons are case-insensitive (uppercased once at precompute time).
        let buildExclusionFilter () : (int -> int -> bool) =
            let refAVG = refMesh.Value.AnnotatedVertexGroups
            let modAVG = modMesh.Value.AnnotatedVertexGroups
            if refAVG.Length = 0 || modAVG.Length = 0 then
                fun _ _ -> false
            else
                let refUncondExcl : bool[] = Array.zeroCreate refAVG.Length
                let refGroups : HashSet<string>[] = Array.zeroCreate refAVG.Length
                for i = 0 to refAVG.Length - 1 do
                    let groups = HashSet<string>()
                    let mutable uncond = false
                    for s in refAVG.[i] do
                        let u = s.ToUpperInvariant()
                        if u = "EXCLUDE" then uncond <- true
                        else groups.Add(u) |> ignore
                    refUncondExcl.[i] <- uncond
                    refGroups.[i] <- groups

                // For mod verts, store just the X tokens of "Exclude.X" / "Include.X".
                let modExcludeTokens : string[][] = Array.zeroCreate modAVG.Length
                let modIncludeTokens : string[][] = Array.zeroCreate modAVG.Length
                let allIncludeTokens = HashSet<string>()
                for i = 0 to modAVG.Length - 1 do
                    let exTokens = ResizeArray<string>()
                    let inTokens = ResizeArray<string>()
                    for s in modAVG.[i] do
                        let u = s.ToUpperInvariant()
                        if u.StartsWith("EXCLUDE.") then
                            exTokens.Add(u.Substring(8))
                        elif u.StartsWith("INCLUDE.") then
                            let token = u.Substring(8)
                            inTokens.Add(token)
                            if allIncludeTokens.Add(token) then
                                let lonce = Logging.getLogOnceFn(md.Name + ref.Name + u, 0)
                                lonce(fun () -> "using inclusion group: " + u)
                    modExcludeTokens.[i] <- exTokens.ToArray()
                    modIncludeTokens.[i] <- inTokens.ToArray()

                // Diagnostic: log once for each ref group that satisfies some mod include directive.
                if allIncludeTokens.Count > 0 then
                    let loggedRefMatches = HashSet<string>()
                    for i = 0 to refAVG.Length - 1 do
                        for g in refGroups.[i] do
                            if allIncludeTokens.Contains(g) && loggedRefMatches.Add(g) then
                                let lonce = Logging.getLogOnceFn(md.Name + ref.Name + g, 0)
                                lonce(fun () -> "found in ref: " + g)

                fun modIdx refIdx ->
                    if refIdx >= refUncondExcl.Length || modIdx >= modExcludeTokens.Length then
                        false
                    elif refUncondExcl.[refIdx] then
                        true
                    else
                        let rgs = refGroups.[refIdx]
                        let exTok = modExcludeTokens.[modIdx]
                        let mutable excluded = false
                        let mutable i = 0
                        while not excluded && i < exTok.Length do
                            if rgs.Contains(exTok.[i]) then excluded <- true
                            i <- i + 1
                        if excluded then true
                        else
                            let inTok = modIncludeTokens.[modIdx]
                            let mutable miss = false
                            let mutable i = 0
                            while not miss && i < inTok.Length do
                                if not (rgs.Contains(inTok.[i])) then miss <- true
                                i <- i + 1
                            miss

        let buildVertRels():VertRel[] =
            let refMesh = refMesh.Value
            let modMesh = modMesh.Value

            // for CPU-skinning mods only: build triangles for ref and mod
            let modTris,refTris =
                match modMesh.Type with
                | CPUReplacement -> buildTris modMesh, buildTris refMesh
                | GPUReplacement
                | GPUAdditive
                | Deletion
                | Reference -> [||],[||]

            let exclusionCheckingEnabled = true

            let exclusionFilter =
                if exclusionCheckingEnabled then buildExclusionFilter()
                else (fun _ _ -> false)

            // for a single mod position index and value, find the relation data
            let getVertRel modIdx (modPos:Vec3F) =
                let closestDist,closestIdx =
                    let mutable currIdx = 0
                    let mutable closestDist = System.Single.MaxValue
                    let mutable closestIdx = -1

                    // This is a straight up, bad-ass linear search through the ref positions.
                    // This loop was pretty hot on the instrumentation profiler, but a lot of that was
                    // because function calls like LengthSquared() only appear to be expensive because of the sheer
                    // number of invocations. They still add up to something, so I reduced the intensity
                    // by "inlining" the vector subtraction/distance calculations.  This saved about 12% on load times.
                    for refPos in refMesh.Positions do
                        let vX = modPos.X - refPos.X
                        let vY = modPos.Y - refPos.Y
                        let vZ = modPos.Z - refPos.Z
                        let lenSqrd = //v.LengthSquared()
                             (vX) * (vX) +
                             (vY) * (vY) +
                             (vZ) * (vZ)

                        if (lenSqrd >= closestDist) || (exclusionFilter modIdx currIdx) then
                            ()
                        else
                            closestDist <- lenSqrd
                            closestIdx <- currIdx
                        currIdx <- currIdx + 1
                    closestDist,closestIdx

                if closestIdx = -1 then
                    // wat
                    failwith "Unable to find closest index; if your mod is using an 'Include.XX' group, group XX may be missing from the ref"

                let closestDist = float32 (Math.Sqrt (float closestDist))

//                do
//                    printfn "%A: %A (%A)" modIdx closestIdx closestDist

                let cpuSkinningData =
                    match modMesh.Type with
                    | Reference
                    | Deletion
                    | GPUAdditive
                    | GPUReplacement -> None
                    | CPUReplacement ->
                        failwith "Looks like its time to implement cpu skinning relation code!"
                        //   CPU-only: find closest triangle containing ref vert
                        //   CPU-only: compute coordinate system
                        None

                {   RefPointIdx = closestIdx;
                    ModVertPos = modPos;
                    RefVertPos = refMesh.Positions.[closestIdx]
                    Distance = closestDist
                    CpuSkinningData = cpuSkinningData }

            // for all mod positions, find the relation data
            let modVertRels = modMesh.Positions |> Array.mapi getVertRel

            // warn if median distance is "large" (could be an indicator of mismatched transforms between ref and mod),
            // in which case the relation is going to be jacked.  This can produce false positives, though.
            modVertRels
                |> Array.sortBy (fun vr -> vr.Distance)
                |> (fun sortedVRs ->
                    let mid = sortedVRs.Length / 2
                    let el = sortedVRs.[mid]
                    if (el.Distance > 1.f) then // threshold here is subjective
                        log.Warn "High median distance detected; ref & mod may not have same scale or other transforms applied: %A" el.Distance
                )

            modVertRels
            
        let buildIt() =
            let binCacheDir = binCacheDir.Trim()
            let useBinCache = 
                if binCacheDir = "" then false
                else 
                    if not (Directory.Exists binCacheDir) then Directory.CreateDirectory binCacheDir |> ignore
                    true

            let loadFresh() = 
                let sw = new Util.StopwatchTracker("MeshRel:" + md.Name + "/" + ref.Name)
                let vertRels = buildVertRels()
                log.Info "built mesh relation from mod '%s' to ref '%s'" md.Name ref.Name
                sw.StopAndPrint()

                vertRels

            modMesh <- Some ((verifyAndGet md.Name md.Mesh).Force())
            refMesh <- Some (ref.Mesh.Force())
                
            let cacheVROpt = 
                if useBinCache then 
                    try 
                        use sw = new Util.StopwatchTracker(sprintf "load mesh rel cache for mod: %A: " md.Name)
                        MeshRelDiskCache.tryLoad binCacheDir md ref 
                    with e -> 
                        log.Error "%A" e
                        None
                else None

            match cacheVROpt with
            | Some cachedVertRels ->
                log.Info "[meshrelcache]: loaded mesh relation from cache for mod '%s' to ref '%s' (cache file: %A)" md.Name ref.Name 
                    (MeshRelDiskCache.relPath binCacheDir md.Name ref.Name )
                cachedVertRels
            | None ->
                let vertRels = loadFresh()

                if useBinCache then
                    try 
                        MeshRelDiskCache.save binCacheDir md ref vertRels
                    with e -> 
                        log.Error "%A" e        
                vertRels

        let vertRels = lazy (buildIt())

        member x.IsBuilt = vertRels.IsValueCreated 
        member x.Build() = vertRels.Force()

        member x.DBMod = md
        member x.DBRef = ref
        /// The binary cache directory this mesh relation was constructed with
        /// (empty string if no cache configured).
        member x.BinCacheDir = binCacheDir

        member x.UpdateDBElems(dbMod,dbRef) = updateDBElems dbMod dbRef

        /// If the MeshRelation has not been built this will be None
        member x.ModMesh = modMesh
        /// If the MeshRelation has not been built this will be None
        member x.RefMesh = refMesh

        member x.VertRelations = vertRels
        member x.ModVertRels = vertRels

        /// If the MeshRelation has not been built this will be None
        member x.GetVertDeclaration() =
            if x.IsBuilt then
                // currently, vertex declaration always comes from the ref
                refMesh.Value.Declaration
            else
                None
