// <auto-generated/>
using System.Reflection;
using System.Runtime.InteropServices;

[assembly: AssemblyTitleAttribute("ModelMod CLR app domain host")]
[assembly: AssemblyDescriptionAttribute("")]
[assembly: GuidAttribute("7b59b7f1-5876-4dd3-abc5-ee380144983d")]
[assembly: AssemblyProductAttribute("ModelMod")]
[assembly: AssemblyVersionAttribute("1.0.0.12")]
[assembly: AssemblyFileVersionAttribute("1.0.0.12")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "1.0.0.12";
    }
}
